/* DO NOT EDIT THIS FILE - it is machine generated */
/*  Copyright (c) 2006, 2011, Oracle and/or its affiliates. All Rights Reserved. */
#include <jni.h>
/* Header for class jsynprog */

#ifndef _Included_jsynprog
#define _Included_jsynprog
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: dir_home */
/* Inaccessible static: log */
/* Inaccessible static: pstart */
/* Inaccessible static: cstart */
/*
 * Class:     jsynprog
 * Method:    Timer
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jsynprog_Timer
  (JNIEnv *, jclass);

/*
 * Class:     jsynprog
 * Method:    cTimer
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jsynprog_cTimer
  (JNIEnv *, jclass);

/*
 * Class:     jsynprog
 * Method:    computeSet
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jsynprog_computeSet
  (JNIEnv *, jclass);

/*
 * Class:     jsynprog
 * Method:    JavaJavaC
 * Signature: (I, I)I
 */
JNIEXPORT jint JNICALL Java_jsynprog_JavaJavaC
  (JNIEnv *, jclass, jint, int);

/*
 * Class:     jsynprog
 * Method:    JavaCC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jsynprog_JavaCC
  (JNIEnv *, jclass, int);

/*
 * Class:     jsynprog
 * Method:    JavaCJava
 * Signature: (I, I)V
 */
JNIEXPORT void JNICALL Java_jsynprog_JavaCJava
  (JNIEnv *, jclass, int);

/*
 * Class:     jsynprog
 * Method:    isJVMPI
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_jsynprog_isJVMPI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
