[^:]*: Assembler messages:
[^:]*:2: Error: the floating-point format has not been set \(or has been disabled\)
[^:]*:3: Error: the floating-point format has not been set \(or has been disabled\)
[^:]*:4: Error: the floating-point format has not been set \(or has been disabled\)
[^:]*:5: Error: the floating-point format has not been set \(or has been disabled\)
[^:]*:6: Error: the floating-point format has not been set \(or has been disabled\)
[^:]*:7: Error: the floating-point format has not been set \(or has been disabled\)
