.TH HDEL 1 05-Apr-1996 HFSUTILS
.SH NAME
hdel \- delete both forks of an HFS file
.SH SYNOPSIS
hdel
.I hfs-path
[...]
.SH DESCRIPTION
.B hdel
deletes files from the current HFS volume. Both forks (resource and data) of
each named file are removed, freeing space for other files.
.SH SEE ALSO
hfsutils(1), hrmdir(1)
.SH FILES
$HOME/.hcwd
.SH AUTHOR
Robert Leslie <rob@mars.org>
