.TH HDIR 1 14-Jan-1997 HFSUTILS
.SH NAME
hdir \- display an HFS directory in long format
.SH SYNOPSIS
hdir
.RI [ options ]
.RI [ hfs-path
.RI ...]
.SH DESCRIPTION
.B hdir
is an alternative interface to
.BR hls .
It is equivalent to supplying
.B hls
the -l flag.
.SH SEE ALSO
hfsutils(1), hls(1)
.SH FILES
$HOME/.hcwd
.SH AUTHOR
Robert Leslie <rob@mars.org>
