.TH HMKDIR 1 13-Jan-1997 HFSUTILS
.SH NAME
hmkdir \- create a new HFS directory
.SH SYNOPSIS
hmkdir
.I hfs-path
[...]
.SH DESCRIPTION
.B hmkdir
creates new, empty directories (folders) on the current HFS volume. There must
not already be a file or directory with each named path.
.SH SEE ALSO
hfsutils(1), hrmdir(1), hcd(1), hpwd(1), hls(1)
.SH FILES
$HOME/.hcwd
.SH AUTHOR
Robert Leslie <rob@mars.org>
