.TH HPWD 1 05-Apr-1996 HFSUTILS
.SH NAME
hpwd \- print the full path to the current HFS working directory
.SH SYNOPSIS
hpwd
.SH DESCRIPTION
.B hpwd
displays the complete (absolute) HFS pathname to the current working directory
on the current volume. The current working directory can be changed with the
.B hcd
command.
.SH SEE ALSO
hfsutils(1), hcd(1)
.SH AUTHOR
Robert Leslie <rob@mars.org>
