.TH HRMDIR 1 05-Apr-1996 HFSUTILS
.SH NAME
hrmdir \- remove an empty HFS directory
.SH SYNOPSIS
hrmdir
.I hfs-path
[...]
.SH DESCRIPTION
.B hrmdir
deletes directories (folders) from the current HFS volume. Each named
directory must already be empty.
.SH SEE ALSO
hfsutils(1), hmkdir(1), hdel(1)
.SH FILES
$HOME/.hcwd
.SH AUTHOR
Robert Leslie <rob@mars.org>
