.*Assembler messages:
.*:5: Error: unrecognized opcode `ldx \$4,\$5\(\$6\)'
.*:6: Error: opcode not supported.* `absq_s\.qb \$3,\$4'
.*:9: Error: opcode not supported.* `lbux \$4,\$5\(\$6\)'
.*:10: Error: opcode not supported.* `absq_s\.qb \$3,\$4'
# ----------------------------------------------------------------------------
.*:18: Error: opcode not supported.* `lbux \$4,\$5\(\$6\)'
.*:19: Error: opcode not supported.* `absq_s\.qb \$3,\$4'
# ----------------------------------------------------------------------------
.*:26: Error: opcode not supported.* `aclr 4,100\(\$4\)'
# ----------------------------------------------------------------------------
.*:29: Warning: the 64-bit microMIPS architecture does not support the `mdmx' extension
.*:30: Error: unrecognized opcode `add.ob \$f4,\$f6,\$f8'
# ----------------------------------------------------------------------------
.*:34: Warning: the 64-bit microMIPS architecture does not support the `mips3d' extension
.*:35: Error: unrecognized opcode `addr.ps \$f4,\$f6,\$f8'
# ----------------------------------------------------------------------------
.*:42: Error: opcode not supported.* `dmt *'
# ----------------------------------------------------------------------------
.*:45: Warning: the 64-bit microMIPS architecture does not support the `smartmips' extension
.*:46: Error: unrecognized opcode `maddp \$4,\$5'
# ----------------------------------------------------------------------------
.*:55: Error: opcode not supported.* `hypcall *'
.*:56: Error: opcode not supported.* `dmfgc0 \$3,\$29'
# ----------------------------------------------------------------------------
.*:64: Error: opcode not supported.* `lbue \$4,16\(\$5\)'
