[^:]*: Assembler messages:
.*: Error: selected processor does not support `fmmla v0.4s,v0.16b,v0.16b'
.*: Error: selected processor does not support `fmmla v0.4s,v0.16b,v31.16b'
.*: Error: selected processor does not support `fmmla v0.4s,v31.16b,v0.16b'
.*: Error: selected processor does not support `fmmla v0.4s,v31.16b,v31.16b'
.*: Error: selected processor does not support `fmmla v31.4s,v0.16b,v0.16b'
.*: Error: selected processor does not support `fmmla v31.4s,v0.16b,v31.16b'
.*: Error: selected processor does not support `fmmla v31.4s,v31.16b,v0.16b'
.*: Error: selected processor does not support `fmmla v31.4s,v31.16b,v31.16b'
