[^ :]+: Assembler messages:
[^ :]+:[0-9]+: Error: operand 1 must be an STSHH policy \(keep/strm\) -- `stshh kee'
[^ :]+:[0-9]+: Error: operand 1 must be an STSHH policy \(keep/strm\) -- `stshh strmm'
[^ :]+:[0-9]+: Error: operand 1 must be an STSHH policy \(keep/strm\) -- `stshh'
[^ :]+:[0-9]+: Error: constant expression required at operand 1 -- `prfm ir1234'
[^ :]+:[0-9]+: Error: invalid addressing mode at operand 2 -- `prfm ir,\[sp,x0,lsl#0\]'
[^ :]+:[0-9]+: Error: invalid addressing mode at operand 2 -- `prfm ir,a'
[^ :]+:[0-9]+: Error: invalid prefetch operation \(IR is not valid for this instruction variant\) at operand 1 -- `prfum ir,\[x0\]'
[^ :]+:[0-9]+: Error: immediate offset out of range
