[^:]*: Assembler messages:
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstart x0'
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstart sa'
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstart zm'
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstop x0'
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstop sa'
[^:]*:[0-9]+: Error: unexpected characters following instruction -- `smstop zm'
