.*: Assembler messages:
.*:3: Warning: .*shortened.*
.*:14:  Info: .*
.*:3: Warning: .*shortened.*
.*:18:  Info: .*
.*:3: Warning: .*shortened.*
.*:22:  Info: .*
.*:3: Warning: .*shortened.*
.*:26:  Info: .*
.*:3: Warning: .*shortened.*
.*:40:  Info: .*
.*:3: Warning: .*shortened.*
.*:62:  Info: .*
.*:3: Warning: .*shortened.*
.*:72:  Info: .*
.*:3: Warning: .*shortened.*
.*:75:  Info: .*
.*:3: Warning: .*shortened.*
.*:79:  Info: .*
