.* Assembler messages:
.*:5: Error: all tmm registers must be distinct for `tdpbf8ps'
.*:6: Error: all tmm registers must be distinct for `tdpbf8ps'
.*:7: Error: all tmm registers must be distinct for `tdpbhf8ps'
.*:8: Error: all tmm registers must be distinct for `tdpbhf8ps'
.*:9: Error: all tmm registers must be distinct for `tdphbf8ps'
.*:10: Error: all tmm registers must be distinct for `tdphbf8ps'
.*:11: Error: all tmm registers must be distinct for `tdphf8ps'
.*:12: Error: all tmm registers must be distinct for `tdphf8ps'
